Feature/data config UI
harshada8989/observability pull request #1
Opened 2022-09-19 14:47 UTC by harshada8989

### Description
Changes implemented in Data Configurations UI panel as per wizard mock

### Issues Resolved
#1020

Note:
Due to some issue duplicate commits got created so that's why there is duplicates commits below

2022-09-20 19:09 UTC, spattnaik requested changes

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_treemap_parents.tsx
> +  const handleAddEditParent = (isAdd: boolean, index: number) => {
Consider separating two methods. There is no point in having add and edit functionality combined and adding checks for add/edit. This type of code should be avoided unless too much functionality is common. In fact, if many functionlaity are common, you can derive them into a smaller function and should call that from both these functions.

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +    const list = { ...configList };
this `list` is not required. This is used only once/twice in the function. We are doing unnecessary spread operator here. The configList can directly be used at the required place.

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +    });
There are multiple problems here:
1. The code looks more like copy/paste, as it follows two style of coding. In the first map function you did an implicit return whereas in the second function, you did explicit return for similar objects.
2. you updated the label to opt.label in the first function, but again updated it to item.name. So the final assignment counts. The initial assignment was unnecessary.
3. These two functions can be combined into one, as you are operating on the same set of objects in both the functions.

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +          }}
This is same as `onChange={handleParentChange}`. The `option` argument is going to be automatically supplied.

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +          aria-label="Use aria labels when no actual label is in use"
Use proper label here. Do not use placeholders. Read about what is `aria-label`.

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_item.tsx
> +      const list = { ...configList };
I do not see you updating this `configList` or `list` variable in this function. Hence I think, it is unnecessary to create another variable just to hold the values of this variable by using a spread operation. Let me know, if I am missing something.

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_item.tsx
> +                      aria-label="Use aria labels when no actual label is in use"
use proper label here

2022-09-20 19:09 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_item.tsx
> +        aria-label="Accessible screen reader label"
Proper label please

2022-09-23 08:43 UTC, harshada8989 commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_treemap_parents.tsx
> +  const handleAddEditParent = (isAdd: boolean, index: number) => {
Created seprate functions

2022-09-23 08:44 UTC, harshada8989 commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +    });
These were existing code which i changed now

2022-09-27 12:14 UTC, ruchika-narang commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +          id={uniqueId('axis-select-')}
We have to use htmlIdGenerator instead of uniqueId..can we do the same here?

2022-09-27 12:24 UTC, ruchika-narang requested changes
Change the uniqueId to htmlIdGenerator if possible. Rest looks good to me

2022-09-27 13:12 UTC, closed without merging

2022-09-29 18:53 UTC, spattnaik reviewed
Few minor comments. Please check the relevance before committing. Otherwise, please reply on the comment.

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/common/query_manager/ast/expression/span.ts
> +      customLabel: this.customLabel,
Why not use the custom label constant here?

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/common/query_manager/ast/types/stats.ts
> +  customLabel: string;
Same comment as above, why not use the constant?

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_treemap_parents.tsx
> +            <>
This Fragment with key is required. We had introduced this to remove many warnings that React gives in the browser console.

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_treemap_parents.tsx
> +              <EuiPanel key={index} paddingSize="s" className="panelItem_button">
key is not required here. Key is required for the base element inside the loop, not the inner elements. If you are using the key for something else, then you can keep it here.

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx
> +  const isHeatMapAddButton = (name: string) => {
You may use useMemo here.

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx
> +          <>
loop's first element should have a key property

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx
> +            <EuiPanel key={index} paddingSize="s" className="panelItem_button">
key may not be required here

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/treemap_config_panel_item.tsx
> +          isClearable={true}
`true` may not be required explicitly for `isClearable`.

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts
> +                  userSelectedConfigs?.dataConfig[GROUPBY]?.length > 0
The question mark after `userSelectedConfigs` may not be required here, as the first expression before && is going to be evaluated first. If that becomes true, then the property `dataConfig` does exist anyway.

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts
> +                    ? [...userSelectedConfigs?.dataConfig[GROUPBY][0][PARENTFIELDS]]
same as above

2022-09-29 18:53 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_item.tsx
> +        <div key={index} className="services">
Is this `key` property required here? This is not a loop - unless you are using the key property for something else.